### ISSUE TITLE
Mirrors url fault!

### ISSUE THREAD

**Issue by AndersonMeng** [archlinuxcn/mirrorlist-repo#1]
Hello:
     I am the administration of Chongqing University Open Source Mirror Site.
     I am very sorry to tell you that the url of archlinux-cn is wrong,the actual url is: http://mirrors.cqu.edu.cn/archlinux-cn/

```
Please help us correct it ASAP,thank you !
```

 Anderson
Contact Mail :mirrors@cmdgy.com

**Comment by felixonmars** [comment]
Fixed, thanks!

**Comment by lilydjwg** [comment]
@AndersonMeng Your [mirror help](http://mirrors.cqu.edu.cn/wiki/index.php?title=ArchLinux) teaches Arch Linux users to treat their systems as Debians. You'd fix that ASAP too.
