### ISSUE TITLE
阿里云添加了archlinuxcn镜像

### ISSUE THREAD

**Issue by abcfy2** [archlinuxcn/mirrorlist-repo#11]
https://developer.aliyun.com/mirror/archlinuxcn

**Comment by lilydjwg** [comment]
延迟三天多……

**Comment by abcfy2** [comment]
![image](https://user-images.githubusercontent.com/5327677/86473201-0c17da80-bd73-11ea-82b4-be3ca86c68ec.png)
我看阿里云的仓库状态还是同步中，在等等看看，如果还是同步失败就去给阿里云提交issue好了。

国内的镜像站我评测过，目前体验最好的就是阿里云了，全国CDN节点最多，速度最快，可用性最好

**Comment by lilydjwg** [comment]
五天了……同步进程卡住了吧。

**Comment by abcfy2** [comment]
已经在阿里云开发者社区反应了，目前还没有阿里云的人员回复。

https://mirrors.aliyun.com/archlinuxcn/ 不过我看这个目录下，有些目录的更新时间已经变了，比如x86_64，但是lastupdate 这个文件的时间依旧停留在6月29日，不知道他们的同步出了什么问题，感觉特别的慢。

**Comment by abcfy2** [comment]
我怀疑是不是上游同步的速度特别慢啊，我用wget[整站下载](https://www.linuxjournal.com/content/downloading-entire-web-site-wget)的方案，看了下阿里云的镜像同步情况，还是有很多404，应该是同步失败或者还没同步成功的:

```
# du -csh *
14G     aarch64
13G     any
12G     arm
12G     armv6h
15G     armv7h
4.0K    header.html
14G     i686
4.0K    index.html
4.0K    lastupdate
13M     pkginfo.db
4.0K    robots.txt
60G     x86_64
138G    总用量
```

暂时不知道archlinuxcn整个仓库到底多大，如果知道的话大概就知道阿里云的同步速度以及多久才能同步完了

**Comment by lilydjwg** [comment]
USTC 那边有写，现在有 70G 了。你用 wget 的话，软链接就没法保持了。
我去服务器上 du 了一下：

```
1.2G    aarch64
17G     any
20M     arm
20M     armv6h
2.7G    armv7h
1.5G    i686
49G     x86_64
```

看起来应该快了吧……

**Comment by abcfy2** [comment]
用du的`-l`和`-L`参数一起用，应该就能计算出实际wget需要下载的大小了，试试:

```shell
du -lLcsh *
```

**Comment by lilydjwg** [comment]
```
17G     aarch64
17G     any
16G     arm
16G     armv6h
19G     armv7h
4.0K    header.html
17G     i686
4.0K    lastupdate
13M     pkginfo.db
4.0K    robots.txt
65G     x86_64
164G    total
```
