### ISSUE TITLE
清华大学镜像站启用CDN版本OpenTUNA

### ISSUE THREAD

**Issue by abcfy2** [archlinuxcn/mirrorlist-repo#12]
对应的ArchlinuxCN镜像地址: https://opentuna.cn/archlinuxcn/

关于OpenTUNA的简介： https://opentuna.cn/news/#opentuna-mirror

PS： 清华大学真的不差钱，直接又搞了个Cloudflare CDN版本的镜像站。如果真的能把tuna所有的镜像全部同步到opentuna上，那么opentuna几乎就是国内的镜像站之王，超高的同步频率超全面的镜像数量，再加上全国CDN加速，基本上是国内镜像站的不二之选

**Comment by Xuanwo** [comment]
纠正一下，opentuna 是 AWS 宁夏跟 TUNA 合作的，CDN 是 AWS 旗下的 Cloudfront，跟 Cloudflare 没有关系（金主的名头可不能说错）

ref: https://aws.amazon.com/cn/blogs/china/the-tuna-open-source-mirroring-station-branch-officially-launched-and-opened-its-services-on-the-aws-china-ningxia-region-operated-by-west-cloud-data/
