### ISSUE TITLE
TUNA 也有 HTTPS，另外不该优先推荐 https 吗？

### ISSUE THREAD

**Issue by Artoria2e5** [archlinuxcn/mirrorlist-repo#2]
（

**Comment by petronny** [comment]
![2015-12-02 23-56-52](https://cloud.githubusercontent.com/assets/5357170/11535797/6f6876f4-9950-11e5-878d-687355cad645.png)
TUNA自己推荐都是http的，╮（￣▽￣）╭

**Comment by Artoria2e5** [comment]
不，有 HTTPS 就推荐 HTTPS 是另外的原则啊……
