### ISSUE TITLE
cnssuestc does't have https support

### ISSUE THREAD

**Issue by zsrkmyn** [archlinuxcn/mirrorlist-repo#3]
It seems that cnssuestc mirror can only be only accessed by http connection but not https. So I think `Server = https://mirrors.cnssuestc.org/archlinuxcn/$arch` should be changed to `Server = http://mirrors.cnssuestc.org/archlinuxcn/$arch`, or ask @KaseiWang or @pandada8 to add https support to this mirror.

**Comment by pandada8** [comment]
Thanks, https support will be added when I am available.
