### ISSUE TITLE
检查镜像的有效性

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/mirrorlist-repo#4]
- [x] 镜像是否仍可访问
- [x] 镜像是否已不再同步

**Comment by wych42** [comment]
mirror.163.com 居然还在。

**Comment by lilydjwg** [comment]
而且它还支持 HTTPS 了。

**Comment by DresserTomsk** [comment]
SSL: no alternative certificate subject name matches target host name 'cdn.repo.archlinuxcn.org'
failed to synchronize all databases

Apparently, the mirror died

**Comment by lilydjwg** [comment]
@DresserTomsk it has revived :-)

**Comment by LEXUGE** [comment]
the mirror of ZJU was deprecated.
