### ISSUE TITLE
The main repo cannot be accessed

### ISSUE THREAD

**Issue by LearnWebGitHub** [archlinuxcn/mirrorlist-repo#50]
Unable to access https://repo.archlinuxcn.org even with VPN, is the repo down?
I recently saw someone on Reddit having the same issue.

**Comment by lilydjwg** [comment]
repo.archlinuxcn.org is currently offline without a timeline to restore. Please use a mirror instead; they will soon resume syncing from our build server.

**Comment by lilydjwg** [comment]
The server is back.
